site_name: НИР 2
site_author: miirld_
site_description: Тема НИР - Выбор и обоснование критериев для сравнения асинхронных веб-фреймворков в экосистеме Python

theme:
  name: null
  custom_dir: theme/

nav:
  - Главная: index.md
  - Источники: references.md

watch:
  - theme